title: Watch Later Button
description: A simple Chrome extension that adds a convenient button to quickly save videos to your "Watch Later" playlist on YouTube.
author: Alex Pletnov

# Set the Jekyll theme
theme: minima

# Add plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Sitemap
url: "https://alxple.github.io"  # Required for correct URLs in sitemap
sitemap:
  include_posts: true  # Include posts (default: true)
  change_frequency: "weekly"  # Change frequency
  priority: 0.5  # Page priority

# Typographer
typographer:
  entities: true  # Enable HTML entities
  quotes: true    # Replace quotes
  dashes: true    # Replace dashes

# Optional: configure URL for posts
permalink: /updates/:year/:month/:day/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - README.md
  - e2e.test.js
  - LICENSE
  - .gitignore
  - package.json
  - package-lock.json
  - chrome/
  - SETUP.md





